<a href="https://colab.research.google.com/github/sadasivam009/bike-sharing-demand-reg-/blob/main/DL_loan_(22_05).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [2]:
data = {
  "income": [20,25,30,35,40,45,50,60,22,28,38,48,55,65,33,43],
  "credit_score": [500,550,580,600,650,680,700,750,520,570,620,690,720,780,610,670],
  "loan_amount": [5,7,8,10,12,14,15,18,6,8,11,13,16,20,9,12],
  "loan_approved": [0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,1]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

    income  credit_score  loan_amount  loan_approved
0       20           500            5              0
1       25           550            7              0
2       30           580            8              0
3       35           600           10              1
4       40           650           12              1
5       45           680           14              1
6       50           700           15              1
7       60           750           18              1
8       22           520            6              0
9       28           570            8              0
10      38           620           11              1
11      48           690           13              1
12      55           720           16              1
13      65           780           20              1
14      33           610            9              1
15      43           670           12              1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   income         16 non-null     int64
 1   credit_score   16 non-null     int64
 2   loan_amount    16 non-null     int64
 3   loan_approved  16 non-null     int64
dtypes: int64(4)
memory usage: 644.0 bytes

In [7]:
df.shape

(16, 4)

In [8]:
df.describe()

          income  credit_score  loan_amount  loan_approved
count  16.000000     16.000000    16.000000      16.000000
mean   39.812500    636.875000    11.500000       0.687500
std    13.462138     81.708323     4.335897       0.478714
min    20.000000    500.000000     5.000000       0.000000
25%    29.500000    577.500000     8.000000       0.000000
50%    39.000000    635.000000    11.500000       1.000000
75%    48.500000    692.500000    14.250000       1.000000
max    65.000000    780.000000    20.000000       1.000000

In [10]:
x = df.drop("loan_approved", axis=1)
y = df["loan_approved"]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [25]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [28]:
model = Sequential()
model.add(Dense(16, input_dim=3, activation="relu"))
model.add(Dense(8,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [30]:
model.compile(loss='binary_crossentropy', optimizer=Adam(learning_rate=0.01), metrics=['accuracy'])

In [31]:
print(model.summary())

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 16)             │            64 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 209 (836.00 B)

 Trainable params: 209 (836.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [54]:
history = model.fit(X_train, y_train, epochs=30, batch_size=4)

Epoch 1/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 3.0247e-04
Epoch 2/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 2.9972e-04
Epoch 3/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 2.9654e-04
Epoch 4/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 2.9305e-04
Epoch 5/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 2.9171e-04
Epoch 6/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 2.8760e-04
Epoch 7/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 2.8636e-04
Epoch 8/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 2.8249e-04
Epoch 9/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 2.8089e-04
Epoch 10/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 2.7904e-04
Epoch 11/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 2.7714e-04
Epoch 12/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 2.7128e-04
Epoch 13/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 2.6902e-04
Epoch 14/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 2.6653e-04
Epoch 15/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 2.6490e-04
Epoch 16/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 2.6196e-04
Epoch 17/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 2.5819e-04
Epoch 18/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 2.5579e-04
Epoch 19/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 2.5352e-04
Epoch 20/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 2.5184e-04
Epoch 21/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 2.5095e-04
Epoch 22/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 2.4804e-04
Epoch 23/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 2.4429e-04
Epoch 24/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 2.4293e-04
Epoch 25/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 2.3899e-04
Epoch 26/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 2.3852e-04
Epoch 27/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 2.3694e-04
Epoch 28/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 2.3372e-04
Epoch 29/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 2.3243e-04
Epoch 30/30
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 2.3089e-04

In [63]:
loss, accuracy = model.evaluate(X_test, y_test)
print(accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 1.0000 - loss: 0.0228
1.0

In [79]:
loan_process = np.array([[30,600,14]])
loan_process = scaler.transform(loan_process)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [80]:
prediction = model.predict(loan_process)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[0.9999536]]

In [81]:
if prediction > 0.5 :
  print("loan approved")
else:
  print("loan not approved")

loan approved